DROP TABLE IF EXISTS runwithit_users;
DROP TABLE IF EXISTS runwithit_runs;

CREATE TABLE runwithit_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    goal_distance FLOAT,
    goal_pace INT
);