DROP TABLE IF EXISTS runwithit_users;
DROP TABLE IF EXISTS runwithit_runs;

CREATE TABLE runwithit_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    goal_distance FLOAT,
    goal_pace INT
);

INSERT INTO runwithit_users(name, email, password, goal_distance, goal_pace)

VALUES
    ('James', 'james@test.com', 'james123', 5, 480),
    ('Amy', 'amy@test.com', 'amy123', 4, 540);