DROP TABLE IF EXISTS runwithit_runs;

CREATE TABLE runwithit_runs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES runwithit_users(id) ON DELETE SET NULL,
    date DATE,
    distance FLOAT,
    time INTEGER,
    note VARCHAR(100)
);
