DROP TABLE IF EXISTS runwithit_runs;

CREATE TABLE runwithit_runs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES runwithit_users(id) ON DELETE SET NULL,
    date DATE,
    distance FLOAT,
    time INTEGER,
    note VARCHAR(100)
);

INSERT INTO runwithit_runs (user_id, distance, date, time, note)

VALUES
    (1, 2, '2021-01-01', 1200, 'Hard run, felt a little slow'),
    (1, 2.4, '2021-01-03', 1460, 'Great run, better than last time'),
    (1, 1.8, '2021-01-05', 1020, 'Fast and short'),
    (1, 3.2, '2021-01-07', 1920, 'Longer run, took it easy'),
    (2, 1, '2021-01-01', 690, 'First run of the year, chill mile'),
    (2, 1.2, '2021-01-03', 792, 'Great run, better than last time'),
    (2, 1.6, '2021-01-05', 810, 'Slightly longer than last run'),
    (2, 2, '2021-01-07', 1380, '2 miles, not bad');